package com.dicoding.firstapplication

object ClubsData {

    private val clubNames = arrayOf("FC Barcelona",
    "Real Madrid CF",
    "Bayern Munich",
    "Manchester United",
    "Liverpool",
    "Manchester City",
    "Chelsea",
    "Arsenal",
    "Paris Saint-Germain",
    "Tottenham Hotspur")

    private val clubDetail = arrayOf("The Spanish giants have been ranked at the top spot among the most valuable football clubs in the world, ending a 16-year hegemony of Manchester United and Real Madrid. The La Liga outfit have earned a similar revenue as that of Los Blancos, in the region of \$792 million, but thanks to lower operating costs, they have narrowly surpassed them. The club dominated the market ahead of the 2020/21 season due to the rumors of their legend Lionel Messi leaving, who later stayed another year.\n" +
            "\n" +
            "Futbol Club Barcelona (Catalan pronunciation: [fubˈbɔl ˈklub bəɾsəˈlonə]), commonly referred to as Barcelona and colloquially known as Barça ([ˈbaɾsə]), is a Spanish professional football club based in Barcelona, Spain, that competes in La Liga, the top flight of Spanish football.\n" +
            "\n" +
            "Founded in 1899 by a group of Swiss, Spanish, German and English footballers led by Joan Gamper, the club has become a symbol of Catalan culture and Catalanism, hence the motto \"Més que un club\" (\"More than a club\"). Unlike many other football clubs, the supporters own and operate Barcelona. It is the fourth-most valuable sports team in the world, worth \$4.06 billion, and the world's richest football club in terms of revenue, with an annual turnover of €840.8 million. The official Barcelona anthem is the \"Cant del Barça\", written by Jaume Picas and Josep Maria Espinàs. Barcelona traditionally play in dark shades of blue and red stripes, leading to the nickname Blaugrana.\n" +
            "\n" +
            "Domestically, Barcelona has won a record 75 trophies: 26 La Liga, 31 Copa del Rey, thirteen Supercopa de España, three Copa Eva Duarte, and two Copa de la Liga titles, as well as being the record holder for the latter four competitions. In international club football, the club has won twenty European and worldwide titles: five UEFA Champions League titles, a record four UEFA Cup Winners' Cups, a joint record five UEFA Super Cups, a record three Inter-Cities Fairs Cups, and three FIFA Club World Cups. Barcelona was ranked first in the International Federation of Football History & Statistics Club World Ranking for 1997, 2009, 2011, 2012, and 2015 and as of 2021, occupies the fourth position on the UEFA club rankings. The club has a long-standing rivalry with Real Madrid, and matches between the two teams are referred to as El Clásico.\n" +
            "\n" +
            "Barcelona is one of the most widely supported teams in the world, and the club has one of the largest social media following in the world among sports teams. Barcelona players have won a record number of Ballon d'Or awards (twelve), with recipients including Johan Cruyff, as well as a record number of FIFA World Player of the Year awards (seven), with winners including Ronaldo, Romário, Ronaldinho, and Rivaldo. In 2010, three players who came through the club's youth academy (Lionel Messi, Andrés Iniesta and Xavi) were chosen as the three best players in the world in the FIFA Ballon d'Or awards, an unprecedented feat for players from the same football academy. Additionally, players representing the club have won a record number (eight) of European Golden Shoe awards.\n" +
            "\n" +
            "Barcelona is one of three founding members of the Primera División that have never been relegated from the top division since its inception in 1929, along with Athletic Bilbao and Real Madrid. In 2009, Barcelona became the first Spanish club to win the continental treble consisting of La Liga, Copa del Rey, and the UEFA Champions League, and also became the first Spanish football club to win six out of six competitions in a single year, by also winning the Spanish Super Cup, UEFA Super Cup, and FIFA Club World Cup. In 2011, the club became European champions again and won five trophies. This Barcelona team, which won fourteen trophies in just four years under Pep Guardiola, is considered by some in the sport to be the greatest team of all time. By winning their fifth Champions League trophy in 2015, Barcelona became the first European football club in history to achieve the continental treble twice. The highest paid sports team in the world, in 2018 Barcelona became the first sports team with average first-team pay in excess of £10 million (\$13.8 million) per year.\n",

        "Real Madrid have been dethroned this time around and have to settle for the second place in the rankings. Their value is in the region of \$4.75 billion, thereby becoming the second-most valuable club in the world. The La Liga giants are one of the most renowned clubs all over the world boasting of a huge fanbase. Their last year’s revenue was gauged to be in the region of \$792 million.\n" +
                "\n" +
                "Real Madrid Club de Fútbol (Spanish pronunciation: [reˈal maˈðɾið ˈkluβ ðe ˈfuðβol], meaning Royal Madrid Football Club), commonly referred to as Real Madrid, is a Spanish professional football club based in Madrid.\n" +
                "\n" +
                "Founded on 6 March 1902 as Madrid Football Club, the club has traditionally worn a white home kit since inception. The honorific title real is Spanish for \"royal\" and was bestowed to the club by King Alfonso XIII in 1920 together with the royal crown in the emblem. The team has played its home matches in the 81,044-capacity Santiago Bernabéu Stadium in downtown Madrid since 1947. Unlike most European sporting entities, Real Madrid's members (socios) have owned and operated the club throughout its history.\n" +
                "\n" +
                "The club was estimated to be worth €3.8 billion (\$4.2 billion) in 2019, and it was the second highest-earning football club in the world, with an annual revenue of €757.3 million in 2019. The club is one of the most widely supported teams in the world. Real Madrid is one of three founding members of La Liga that have never been relegated from the top division since its inception in 1929, along with Athletic Bilbao and Barcelona. The club holds many long-standing rivalries, most notably El Clásico with Barcelona and El Derbi Madrileño with Atlético Madrid.\n" +
                "\n" +
                "Real Madrid established itself as a major force in both Spanish and European football during the 1950s, winning five consecutive European Cups and reaching the final seven times. This success was replicated in the league, which the club won five times in the space of seven years. This team, which included Alfredo Di Stéfano, Ferenc Puskás, Francisco Gento, and Raymond Kopa, is considered by some in the sport to be the greatest team of all time.\n" +
                "\n" +
                "In domestic football, the club has won 66 trophies; a record 34 La Liga titles, 19 Copa del Rey, 11 Supercopa de España, a Copa Eva Duarte, and a Copa de la Liga. In European and worldwide competitions, Real Madrid have won a record 26 trophies; a record 13 European Cup/UEFA Champions League titles, two UEFA Cups and four UEFA Super Cups. In international football, they have achieved a record seven club world championships.\n" +
                "\n" +
                "Real Madrid was recognised as the FIFA Club of the 20th Century on 11 December 2000 with 42.35% of the vote, and received the FIFA Centennial Order of Merit on 20 May 2004. The club was also awarded Best European Club of the 20th Century by the IFFHS on 11 May 2010. In June 2017, the team succeeded in becoming the first club to win consecutive Champions League titles, then made it three in a row and four in five seasons in May 2018, extending their lead atop the UEFA club rankings. As of 2020, Real Madrid are ranked third behind Bayern Munich and Barcelona.",

        "Heading into the top three, Germany’s FC Bayern Munich are the third most valuable club and the most valuable from the Bundesliga. They are valued around \$4.215 billion, narrowly overtaking Manchester United. The defending UCL winners also secured the Bundesliga and the FIFA Club World Cup among other honors in 2020. Their winning efforts earned them a huge revenue of \$703 million last year.\n" +
                "\n" +
                "Fußball-Club Bayern München e. V. (German pronunciation: [ˈfuːsbalˌklʊp ˈbaɪɐn ˈmʏnçn̩]), commonly known as FC Bayern München (German pronunciation: [ˌɛftseː ˈbaɪɐn ˈmʏnçn̩]), FCB, Bayern Munich, or FC Bayern, is a German professional sports club based in Munich, Bavaria. It is best known for its professional football team, which plays in the Bundesliga, the top tier of the German football league system. Bayern is the most successful club in German football history, having won a record 31 national titles, including nine consecutively since 2013, and 20 national cups, along with numerous European honours.\n" +
                "\n" +
                "FC Bayern Munich was founded in 1900 by 11 football players, led by Franz John. Although Bayern won its first national championship in 1932, the club was not selected for the Bundesliga at its inception in 1963. The club had its period of greatest success in the mid-1970s when, under the captaincy of Franz Beckenbauer, it won the European Cup three consecutive times (1974–1976). Overall, Bayern have won six European Cup/UEFA Champions League titles (German record), winning their sixth title in the 2020 final as part of a continental treble, after which it became only the second European club to achieve the continental treble twice. Bayern has also won one UEFA Cup, one European Cup Winners' Cup, two UEFA Super Cups, two FIFA Club World Cups and two Intercontinental Cups, making it one of the most successful European clubs internationally and the only German club to have won both international titles.\n" +
                "\n" +
                "By winning the 2020 FIFA Club World Cup, Bayern Munich became only the second club to win the sextuple. Bayern Munich are one of five clubs to have won all three of UEFA's main club competitions, the only German club to achieve that. As of May 2021, Bayern Munich are ranked first in UEFA club rankings. The club has traditional local rivalries with 1860 Munich and 1. FC Nürnberg, as well as with Borussia Dortmund since the mid-1990s.\n" +
                "\n" +
                "Since the beginning of the 2005–06 season, Bayern has played its home games at the Allianz Arena. Previously the team had played at Munich's Olympiastadion for 33 years. The team colours are red and white, and the crest shows the white and blue flag of Bavaria. In terms of revenue, Bayern Munich is the largest sports club in Germany and the third highest-earning football club in the world, behind FC Barcelona and Real Madrid, with a value of €634.1 million in 2021. In November 2019, Bayern had 293,000 official members and 4,499 officially registered fan clubs with over 350,000 members. The club has other departments for chess, handball, basketball, gymnastics, bowling, table tennis and senior football with more than 1,100 active members.\n",

        "Manchester United have slipped out of the top three and settled in the fourth place. The club is valued at \$4.2 billion. The Red Devils remain Premier League’s most valuable football club, despite not winning the league title since the 2012/2013 season. Thanks to their massive fanbase all over the globe, merchandise sales and market dominance, United were able to generate a revenue of \$643 million in 2020.\n" +
                "\n" +
                "Manchester United Football Club is a professional football club based in Old Trafford, Greater Manchester, England, that competes in the Premier League, the top flight of English football. Nicknamed \"the Red Devils\", the club was founded as Newton Heath LYR Football Club in 1878, changed its name to Manchester United in 1902 and moved to its current stadium, Old Trafford, in 1910.\n" +
                "\n" +
                "Manchester United have won more trophies than any other club in English football, with a record 20 League titles, 12 FA Cups, five League Cups and a record 21 FA Community Shields. United have also won three European Cups/UEFA Champions Leagues, one UEFA Europa League, one UEFA Cup Winners' Cup, one UEFA Super Cup, one Intercontinental Cup and one FIFA Club World Cup. In 1998–99, the club became the first in the history of English football to achieve the continental European treble. By winning the UEFA Europa League in 2016–17, they became one of five clubs to have won all three main UEFA club competitions.\n" +
                "\n" +
                "The 1958 Munich air disaster claimed the lives of eight players. In 1968, under the management of Matt Busby, Manchester United became the first English football club to win the European Cup. Alex Ferguson won 38 trophies as manager, including 13 Premier League titles, 5 FA Cups and 2 UEFA Champions Leagues, between 1986 and 2013, when he announced his retirement. Manchester United is one of the most widely supported football clubs in the world, and has rivalries with Liverpool, Manchester City, Arsenal and Leeds United.\n" +
                "\n" +
                "Manchester United was the highest-earning football club in the world for 2016–17, with an annual revenue of €676.3 million, and the world's third most valuable football club in 2019, valued at £3.15 billion (\$3.81 billion). After being floated on the London Stock Exchange in 1991, the club was taken private after a purchase by Malcolm Glazer in 2005 at almost £800 million, of which over £500 million of borrowed money became the club's debt. From 2012, some shares of the club were listed on the New York Stock Exchange, although the Glazer family retains overall ownership and control of the club.",

        "Premier League 2019-20 champions Liverpool occupies the fifth spot among the most valuable football clubs in 2021 with a valuation of \$4.1 billion. The defending Premier League champions have been in a breathtaking phase over the past couple of years, also winning the UCL in the process. Their value has increased a whopping 88% in terms of two-year change.\n" +
                "\n" +
                "Liverpool is a city and metropolitan borough in Merseyside, England. With a population of 498,042 in 2019, it is the tenth largest English district by population, and its metropolitan area is the fifth largest in the United Kingdom with a population of 2.24 million.\n" +
                "\n" +
                "Situated on the eastern side of the Mersey Estuary, Liverpool historically lay within the ancient hundred of West Derby in the county of Lancashire. It became a borough in 1207, a city in 1880, and a county borough independent of the newly-created Lancashire County Council in 1889. Its growth as a major port was paralleled by the expansion of the city throughout the Industrial Revolution. Along with general cargo, freight, and raw materials such as coal and cotton, merchants were involved in the slave trade. In the 19th century, Liverpool was a major port of departure for English and Irish emigrants to North America. It was also home to both the Cunard and White Star Lines, and was the port of registry of the ocean liners RMS Titanic, RMS Lusitania, RMS Queen Mary, and RMS Olympic.\n" +
                "\n" +
                "In 2019, Liverpool was the fifth most visited UK city. It is noted for its culture, architecture, and transport links. The city is closely associated with music; the popularity of the Beatles, widely regarded as the most influential band of all time, led to it becoming a tourist destination. Liverpool has continued to be the home of numerous notable musicians and record labels—musicians from the city have released 56 No. 1 hit singles, more than any other city in the world. The city also has a long-standing reputation for producing countless actors and actresses, artists, athletes, comedians, journalists, novelists, and poets. Liverpool has the second highest number of art galleries, national museums, listed buildings, and listed parks in the UK; only the capital, London, has more. The former Liverpool Maritime Mercantile City includes the Pier Head, Albert Dock, and William Brown Street. In sports, the city is best known for being the home of Premier League football teams Liverpool FC and Everton FC, with matches between the two rivals being known as the Merseyside derby. The annual Grand National horse race takes place at Aintree Racecourse.\n" +
                "\n" +
                "Several areas of Liverpool city centre carried World Heritage Site status from 2004 until 2021, and the city's vast collection of parks and open spaces has been described as the \"most important in the country\" by England's Register of Historic Parks and Gardens of Special Historic Interest.[20] Its status as a port city historically attracted a diverse population from a wide range of cultures (primarily Ireland, Norway, and Wales). It is also home to the oldest black community in the UK and the oldest Chinese community in Europe. Natives of Liverpool (and occasionally longtime residents) are formally referred to as \"Liverpudlians\" but are more often called \"Scousers\", a reference to the form of stew made popular by sailors in the city, which also became the most common name for the local accent and dialect. The city celebrated its 800th anniversary in 2007 and was named the 2008 European Capital of Culture, which it shared with the Norwegian city of Stavanger. Its designation as European Capital of Culture resulted in a sharp uptick in the city's fortunes, as the money gained from the EU was spent on regenerating large parts of the city that had become run down.",

        "Manchester City are next up in sixth position. The seven-time English champions are valued at \$4 billion. Their roster has some of the best players and is the most expensive in terms of wages. Thanks to continued success in the domestic sphere, the Manchester-based club is expanding globally in terms of fans and market presence, raking in a lot of revenue as a result.\n" +
                "\n" +
                "Manchester City Football Club is an English football club based in Manchester that competes in the Premier League, the top flight of English football. Founded in 1880 as St. Mark's (West Gorton), it became Ardwick Association Football Club in 1887 and Manchester City in 1894. The club's home ground is the Etihad Stadium in east Manchester, to which it moved in 2003, having played at Maine Road since 1923. The club adopted their sky blue home shirts in 1894 in the first season of the club's current iteration, and have been used ever since.\n" +
                "\n" +
                "Manchester City entered the Football League in 1892, and won their first major honour with the FA Cup in 1904. The club had its first major period of success in the late 1960s, winning the League, European Cup Winners Cup, FA Cup and League Cup under the management of Joe Mercer and Malcolm Allison. After losing the 1981 FA Cup Final, the club went through a period of decline, culminating in relegation to the third tier of English football for the only time in its history in 1998. They since regained promotion to the top tier in 2001–02 and have remained a fixture in the Premier League since 2002–03.\n" +
                "\n" +
                "In 2008, Manchester City was purchased by Abu Dhabi United Group for £210 million and received considerable financial investment in both playing staff and club facilities, including the £150 million Etihad Campus in east Manchester. Under the management of Pep Guardiola, the team won the Premier League in 2018, becoming the only Premier League team to attain 100 points in a single season. In 2019, they won four trophies, completing an unprecedented sweep of all domestic trophies in England and becoming the first English men's team to win the domestic treble.\n" +
                "\n" +
                "Manchester City's revenue was the fifth-highest of a football club in the world in the 2018–19 season at €568.4 million. In 2019, Forbes estimated the club was the fifth most valuable in the world at \$2.69 billion. The club is owned by the City Football Group, a British-based holding company valued at £3.73 (US\$4.8) billion in November 2019 following a 10% stake sale to Silver Lake.",

        "Seventh place is occupied by Chelsea, yet another club from England’s top-flight. The London-based outfit is valued around \$3.2 billion. The Blues have brought in a revenue of \$520 million, much of it could be due to securing UCL qualification, after finishing fourth in the final league standings.\n" +
                "\n" +
                "Chelsea Football Club are an English professional football club based in Fulham, West London. Founded in 1905, the club competes in the Premier League, the top division of English football. Chelsea are among England's most successful clubs, having won over thirty competitive honours, including six league titles and eight European trophies. Their home ground is Stamford Bridge.\n" +
                "\n" +
                "Chelsea won their first major honour, the League championship, in 1955. The club won the FA Cup for the first time in 1970 and their first European honour, the Cup Winners' Cup, in 1971. After a period of decline in the late 1970s and 1980s, the club enjoyed a revival in the 1990s and had more success in cup competitions. The past two decades have been the most successful in Chelsea's history: they have won five Premier League titles, two UEFA Champions League titles and two UEFA Europa League titles during this period. Chelsea are one of five clubs to have won all three of UEFA's main club competitions, the first English club to achieve the UEFA treble, the only London club to have won the Champions League and the only club to have won all three major European competitions twice.\n" +
                "\n" +
                "Chelsea's home kit colours are royal blue shirts and shorts with white socks. The club's crest features a ceremonial lion rampant regardant holding a staff. The club has rivalries with neighbouring teams Arsenal and Tottenham Hotspur, and a historic rivalry with Leeds United. Based on attendance figures, the club has the sixth-largest fanbase in England. In terms of club value, Chelsea are the sixth most valuable football club in the world, worth £2.13 billion (\$2.576 billion), and are the eighth highest-earning football club in the world, with earnings of over €428 million in the 2017–18 season. Since 2003, Chelsea have been owned by Russian-Israeli billionaire Roman Abramovich.",

        "The next spot goes to another Premier League outfit Arsenal. The London-based club is valued at \$2.8 billion. The Gunners are historically rich in trophies and accolades but have struggled to emulate their glories of the past recently. Despite missing out on qualifying for UEFA Champions League last year, the club has accumulated a lot of revenue due to a strong market presence.\n" +
                "\n" +
                "Arsenal Football Club is a professional football club based in Islington, London, England. Arsenal plays in the Premier League, the top flight of English football. The club has won 13 league titles (including one unbeaten title), a record 14 FA Cups, two League Cups, 16 FA Community Shields, the League Centenary Trophy, one European Cup Winners' Cup, and one Inter-Cities Fairs Cup.\n" +
                "\n" +
                "Arsenal was the first club from the South of England to join the Football League, in 1893, and they reached the First Division in 1904. Relegated only once, in 1913, they continue the longest streak in the top division, and have won the second-most top-flight matches in English football history. In the 1930s, Arsenal won five League Championships and two FA Cups, and another FA Cup and two Championships after the war. In 1970–71, they won their first League and FA Cup Double. Between 1989 and 2005, they won five League titles and five FA Cups, including two more Doubles. They completed the 20th century with the highest average league position.\n" +
                "\n" +
                "Herbert Chapman, who changed the fortunes of Arsenal forever, won the club its first silverware, and his legacy led the club to dominate the 1930s decade; Chapman, however, died of pneumonia in 1934, aged 55. He helped introduce the WM formation, floodlights, and shirt numbers; he also added the white sleeves and brighter red to the club's jersey.Arsène Wenger is the longest-serving manager and won the most trophies. He won a record seven FA Cups, and his title-winning team set an English record for the longest top-flight unbeaten league run at 49 games between 2003 and 2004, receiving the nickname The Invincibles.\n" +
                "\n" +
                "In 1886, munitions workers at the Royal Arsenal in Woolwich founded the club as Dial Square. In 1913, the club crossed the city to Arsenal Stadium in Highbury, becoming close neighbours of Tottenham Hotspur, and creating the North London derby. In 2006, they moved to the nearby Emirates Stadium. With an annual revenue of €388m in the 19–20 season, Arsenal was estimated to be worth US\$2.68 billion by Forbes, making it the world's seventh most valuable club, while it is one of the most followed on social media. The motto of the club has long been Victoria Concordia Crescit, Latin for \"Victory Through Harmony\".\n",

        "Ligue 1 defending champions Paris Saint-Germain are next up in the list of most valuable football clubs in 2021 with a valuation of \$2.5 billion. The club is run extremely professionally by the owners, racking up a revenue of \$599 million in 2020 without any debt to boot. They also have some of the most expensive players in their rosters in Neymar and Kylian Mbappe.\n" +
                "\n" +
                "Paris Saint-Germain Football Club (French pronunciation: \u200B[paʁi sɛ̃ ʒɛʁmɛ̃]), commonly referred to as PSG, Paris or Paris SG, is a professional football club based in Paris, France. They compete in Ligue 1, the top division of French football. France's most successful club, they have won over 40 official honours, including nine league titles and one major European trophy. Their home ground is the Parc des Princes.\n" +
                "\n" +
                "Founded in 1970, the Parisians won their first major honour, the French Cup, in 1982 and their first Ligue 1 title in 1986. The 1990s was among the most successful periods in PSG's history; they claimed a second league, three French Cups, two French League Cups, two French Super Cups and the UEFA Cup Winners' Cup in 1996. After suffering a decline in fortunes during the 2000s, the Red and Blues have enjoyed a revival since 2011 with increased financial backing, achieving unparalleled dominance in domestic competitions, winning seven league titles and twenty national cups. PSG have also become a regular feature in the UEFA Champions League, reaching their first final in 2020.\n" +
                "\n" +
                "PSG are the club with most consecutive seasons playing in the top-flight and one of only two French clubs to have won a major European title. They are also the most popular football club in France and one of the most widely supported teams in the world. PSG's home kit colours are red, blue and white, and the club's crest features the Eiffel Tower and a fleur de lys. PSG have a long-standing rivalry with Olympique de Marseille. The duo contest French football's most notorious match, known as Le Classique.\n" +
                "\n" +
                "Tamim bin Hamad Al Thani, the Emir of Qatar, owns PSG through closed shareholders Qatar Sports Investments (QSI), which purchased the club in 2011. The takeover made PSG the richest club in France and one of the wealthiest in the world. As of the 2019–20 season, PSG have the seventh-highest revenue in the footballing world with an annual revenue of €541m according to Deloitte, and are the world's ninth-most valuable football club, worth \$2.5bn according to Forbes.",

        "London-based Tottenham Hotspur are tenth in rankings, with a value of \$2.3 billion. The club have completed the construction of their state of the art Tottenham Hotspur stadium, which took a large chunk of revenue to be finished. Their revenue over the past year stands at \$494 million. \n" +
                "\n" +
                "Tottenham Hotspur Football Club, commonly referred to as Tottenham (/ˈtɒtənəm/) or Spurs, is an English professional football club based in Tottenham, London, that competes in the Premier League, the top flight of English football. The team has played its home matches in the 62,850-capacity Tottenham Hotspur Stadium since April 2019, replacing their former home of White Hart Lane, which had been demolished to make way for the new stadium on the same site.\n" +
                "\n" +
                "Founded in 1882, Tottenham's emblem is a cockerel standing upon a football, with the Latin motto Audere est Facere (\"to dare is to do\"). The club has traditionally worn white shirts and navy blue shorts home kit since the 1898–99 season. Their training ground is on Hotspur Way in Bulls Cross in the London Borough of Enfield. After its inception, Tottenham won the FA Cup for the first time in 1901, the only non-League club to do so since the formation of the Football League in 1888. Tottenham were the first club in the 20th century to achieve the League and FA Cup Double, winning both competitions in the 1960–61 season. After successfully defending the FA Cup in 1962, in 1963 they became the first British club to win a UEFA club competition – the European Cup Winners' Cup. They were also the inaugural winners of the UEFA Cup in 1972, becoming the first British club to win two different major European trophies. They collected at least one major trophy in each of the six decades from the 1950s to 2000s – an achievement only matched by Manchester United.\n" +
                "\n" +
                "In domestic football, Spurs have won two league titles, eight FA Cups, four League Cups, and seven FA Community Shields. In European football, they have won one European Cup Winners' Cup and two UEFA Cups. Tottenham were also runners-up in the 2018–19 UEFA Champions League. They have a long-standing rivalry with nearby club Arsenal, with whom they contest the North London derby. Tottenham is owned by ENIC Group, which purchased the club in 2001. The club was estimated to be worth £1.67 billion (\$2.3 billion) in 2021, and it was the ninth highest-earning football club in the world, with an annual revenue of £390.9 million in 2020.")

    private val clubImage = intArrayOf(R.drawable.barca_logo,
    R.drawable.madrid_logo,
    R.drawable.munchen_logo,
    R.drawable.mu_logo,
    R.drawable.liverpool_logo,
    R.drawable.city_logo,
    R.drawable.chelsea_logo,
    R.drawable.arsenal_logo,
    R.drawable.psg_logo,
    R.drawable.tottenham_logo)

    val listData: ArrayList<Club>
    get() {
        val list = arrayListOf<Club>()
        for (position in clubNames.indices) {
            val club = Club()
            club.name = clubNames[position]
            club.detail = clubDetail[position]
            club.photo = clubImage[position]
            list.add(club)
        }
        return list
    }

}